#ifndef MINIX_DEVICE_MESSAGE_TYPES_HPP__
#define MINIX_DEVICE_MESSAGE_TYPES_HPP__

#define DEVICE_INTERRUPT  HARD_INT
#define DEVICE_READ       DEV_READ
#define DEVICE_WRITE      DEV_WRITE
#define DEVICE_IO_CONTROL DEV_IOCTL
#define DEVICE_OPEN       DEV_OPEN
#define DEVICE_CLOSE      DEV_CLOSE
#define DEVICE_SCATTER    DEV_SCATTER
#define DEVICE_GATHER     DEV_GATHER
#define DEVICE_CANCEL     CANCEL

#endif
